### ISSUE TITLE
[feature request] num_workers option in BPELearner

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/Tokenizer#309]
like this:
https://github.com/rsennrich/subword-nmt/blob/master/subword_nmt/learn_bpe.py#L274

**Comment by guillaumekln** [comment]
Note that this option barely decreases the learning time in subword-nmt. For 4,5M lines and 32000 symbols, it is only 12% faster when using 6 workers instead of 1.

This is because it is only used when reading the input file. The most time consuming part is usually the [loop](https://github.com/rsennrich/subword-nmt/blob/master/subword_nmt/learn_bpe.py#L303) to generate each symbol, but this loop is not easy to parallelize.

**Comment by vince62s** [comment]
Does sentencepiece have the same limitation ?

**Comment by guillaumekln** [comment]
SentencePiece uses multiple threads in 2 places:

* when normalizing the sentences
* when training the Unigram model with the EM algorithm.

By default it uses all available CPU cores and this can be controlled here by setting `num_threads` when creating a `SentencePieceLearner`.

But like subword-nmt, there is no parallelization when learning the BPE model itself.
