### ISSUE TITLE
A strange segmentation occurs with a Thai example.

### ISSUE THREAD

**Issue by l-k-11235** [OpenNMT/Tokenizer#313]
Is this the expected behavior ?
```python
import pyonmttok
th_string = "คุณอาจจะทำอย ่ างนั ้ นไปซักพัก จนคุณเริ ่ มจะรู ้ สึกถึงมันจริงๆ"
tokenizer = pyonmttok.Tokenizer("aggressive", joiner_annotate=True,
	preserve_placeholders= True,
	case_markup=True,
	soft_case_regions=True)
tokens = tokenizer(th_string)
print(tokens)
````
```shell
['คุณอาจจะทำอย', '￭％0020่', 'างนั', '￭％0020้', 'นไปซักพัก', 'จนคุณเริ', '￭％0020่', 'มจะรู', '￭％0020้', 'สึกถึงมันจริงๆ']
```
The output is more consistent with the mode "none":
```python
import pyonmttok
th_string = "คุณอาจจะทำอย ่ างนั ้ นไปซักพัก จนคุณเริ ่ มจะรู ้ สึกถึงมันจริงๆ"
tokenizer = pyonmttok.Tokenizer("none", joiner_annotate=True,
	preserve_placeholders= True,
	soft_case_regions=True)
tokens = tokenizer(th_string)
print(tokens)
````
```shell
['คุณอาจจะทำอย ่ างนั ้ นไปซักพัก จนคุณเริ ่ มจะรู ้ สึกถึงมันจริงๆ']
```

**Comment by francoishernandez** [comment]
Might be linked to https://github.com/OpenNMT/Tokenizer/issues/57 ?

**Comment by guillaumekln** [comment]
The output is expected given the current implementation. We assume that combining marks always modify the previous character. In this example the previous character is a space so we include it in the final token. The space character is also encoded so that it can be written in a text file where tokens are space-separated.

The output looks weird but it should not cause any issue when building the vocabulary or training a model.

**Comment by francoishernandez** [comment]
Makes sense for this example indeed.

I think we might have another issue though, because we do have some weird generations with some trained models. 
E.g. generation of `ก ่` (E0 B8 81 20 E0 B9 88) instead of `ก่` (E0 B8 81 E0 B9 88).
In the aforementioned setup, we also observe some weird merge operations in the bpe file learned with `Tokenizer`:
```
％002 0่</w>
％002 0้</w>
```
![Screenshot from 2023-02-17 18-46-26](https://user-images.githubusercontent.com/14880403/219733078-b8def27b-2e07-4d61-90aa-7c24e90a59f6.png)

`subword-nmt` on the other hand seems to handle such characters fine:
![Screenshot from 2023-02-17 18-46-13](https://user-images.githubusercontent.com/14880403/219733227-40b10cf1-b7f5-40e6-b7d3-4e7d9e6e9f71.png)

Might be linked to some of the other tokenization flags we use, did not test all cases yet.

Any idea welcome.

**Comment by guillaumekln** [comment]
I propose to add a new tokenization options `allow_isolated_marks` to detach the combining mark from the previous character in specific conditions.

Can you have a look at the option documentation and tests in the PR above? Let me know if that makes sense to you, and if there are more cases to consider.

**Comment by francoishernandez** [comment]
Looks like most of our issues stemmed from some bad input data, but some edge cases might remain (still under investigation).
So, having some way to explicitly handle this more cleanly is welcome. Just had a look at #316 and this looks like a clean solution to me. Thanks a lot!
I don't have other cases off the top of my head, but @l-k-11235 might identify some in upcoming exps. We can probably merge this first iteration though, not to leave this hanging too long.
