### ISSUE TITLE
issue with tokenizer in bpe mode

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/Tokenizer#83]
To reproduce, take the corpus: news-commentary-v14.en-ru.ru from WMT19

cat news-commentary-v14.en-ru.ru | ~/Tokenizer/build/cli/tokenize > news-commentary-v14.en-ru.ru.pretok
subword-nmt learn-bpe -s 300 < news-commentary-v14.en-ru.ru.pretok > bpe.model

subword-nmt apply-bpe -c bpe.model < news-commentary-v14.en-ru.ru > news-commentary-v14.en-ru.ru.nopretok.apply_tok
compute vocab on this output => 764 tokens

subword-nmt apply-bpe -c bpe.model < news-commentary-v14.en-ru.ru.pretok > news-commentary-v14.en-ru.ru.pretok.apply_tok
compute vocab on this output => 722 tokens

cat news-commentary-v14.en-ru.ru | ~/Tokenizer/build/cli/tokenize -b bpe.model --joiner_annotate > news-commentary-v14.en-ru.ru.nopretok.omnttok
compute vocab on this output => 830 tokens

cat news-commentary-v14.en-ru.ru.pretok | ~/Tokenizer/build/cli/tokenize -b bpe.model --joiner_annotate > news-commentary-v14.en-ru.ru.pretok.omnttok
compute vocab on this putput => 725 tokens

**Comment by guillaumekln** [comment]
Actually, the only valid command line is this one (the 3rd):

> cat news-commentary-v14.en-ru.ru | ~/Tokenizer/build/cli/tokenize -b bpe.model --joiner_annotate > news-commentary-v14.en-ru.ru.nopretok.omnttok

Here's why:

> 1. subword-nmt apply-bpe -c bpe.model < news-commentary-v14.en-ru.ru > news-commentary-v14.en-ru.ru.nopretok.apply_tok

Not valid because apply-bpe splits on spaces which does not match the tokenization used for learn-bpe.

> 2. subword-nmt apply-bpe -c bpe.model < news-commentary-v14.en-ru.ru.pretok > news-commentary-v14.en-ru.ru.pretok.apply_tok

Not valid because the pretok has no joiner and thus the output is not reversible.

> 3. cat news-commentary-v14.en-ru.ru | ~/Tokenizer/build/cli/tokenize -b bpe.model --joiner_annotate > news-commentary-v14.en-ru.ru.nopretok.omnttok

Correct way to apply the model.

> 4. cat news-commentary-v14.en-ru.ru.pretok | ~/Tokenizer/build/cli/tokenize -b bpe.model --joiner_annotate > news-commentary-v14.en-ru.ru.pretok.omnttok

Not valid, same as the second command.

---

You can compare that the BPE model is applied to same way by both tools with these commands:

```
subword-nmt apply-bpe -c bpe.model -s "" < news-commentary-v14.en-ru.ru.pretok > news-commentary-v14.en-ru.ru.pretok.apply_tok
cat news-commentary-v14.en-ru.ru.pretok | ~/Tokenizer/build/cli/tokenize -b bpe.model > news-commentary-v14.en-ru.ru.pretok.omnttok
diff news-commentary-v14.en-ru.ru.pretok.apply_tok news-commentary-v14.en-ru.ru.pretok.omnttok
```

There are still 4 lines that differ but this comes from apply-bpe that fails to handle some combining marks (e.g. и˘ in output instead of й). So there is no issue as far as I can tell.

**Comment by francoishernandez** [comment]
I have another question linked to this previous discussion. It lies with sequences like `｟some_placeholder｠word`, where there is no space between the placeholder and the word. 
When learning the subword model, placeholders are ignored, so either `▁word` (spacer) or `word` (no joiner) will be learnt.
Though, when tokenizing, the behaviour won't be equivalent between the spacer and the joiner case.
- Joiner:
`｟some_placeholder｠word` --> `｟some_placeholder｠ ￭ word` (no additional token `￭ word` in vocab)

- Spacer:
`｟some_placeholder｠word` --> `｟some_placeholder｠ word` (additional token `word` in vocab, since `▁word` is the one that was learnt.

**Would you encourage to always use joiner instead of spacer?**

_Note_:
If yes, we tried using `--joiner_annotate` when tokenizing with a sentencepiece model.
It leads to other issues for cases like `word｟some_placeholder｠` when keeping `--mode none`. -->  `word￭｟some_placeholder｠` (with `word￭` that does not already exist in vocab).
So, we tested with `--mode conservative` and it seems to be alright, and reversible.

(Tagging @ZengLinxiao FHI)

**Comment by guillaumekln** [comment]
It should be equally valid to use joiners instead of spacers with SentencePiece. I don't really encourage one or the other but the example you showed does indeed highlight an advantage for joiners in the context of placeholders.

Then regarding your note, it seems `--mode none` is not very smart about joiner placement at the moment. It should be improved to not attach the joiners to the previous word nor to the placeholder. I think we can enable this behavior when `preserve_segmented_tokens` is used (*).

Also, let's remember that if it is just about solving the vocabulary issue you could always use `spacer_new` or `joiner_new` which never attach markers to tokens.

---

(*) On a related subject, these options starting with `preserve_` address similar issues. It seems your first joiner example was produced with `preserve_placeholders`. They should probably be enabled by default but are not for backward compatibility reasons.
