### ISSUE TITLE
Installation paths

### ISSUE THREAD

**Issue by chazanov** [OpenNMT/Tokenizer#91]
I would like to package Tokenizer for ArchLinux. For this task the install path must be `/usr/` instead of `/usr/local` and `/usr/local/lib64/` should move to `/usr/lib`.

May you please tell me the right CMake options?

**Comment by guillaumekln** [comment]
See [`CMAKE_INSTALL_PREFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) to set the installation directory.

Regarding `lib` instead of `lib64`, we are using [`GNUInstallDirs`](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) which should provide the standard directory based on the current system. You could possibly override each variable.
